### ISSUE TITLE
PdbxReader fails on reading when _atom_site.auth_asym_id is "_"

### ISSUE THREAD

**Issue by bienchen** [rcsb/py-mmcif#10]
Hello,

when reading a mmCIF file with the PdbxReader, it throws an exception when `_atom_site.auth_asym_id` is "\_".

Here is a minimalistic example to reproduce the behaviour:

```
from io import StringIO
from mmcif.io.PdbxReader import PdbxReader

cif_fragment = """
data_TEST
loop_
_atom_site.group_PDB
_atom_site.id
_atom_site.type_symbol
_atom_site.label_atom_id
_atom_site.label_alt_id
_atom_site.label_comp_id
_atom_site.label_seq_id
_atom_site.auth_seq_id
_atom_site.pdbx_PDB_ins_code
_atom_site.label_asym_id
_atom_site.Cartn_x
_atom_site.Cartn_y
_atom_site.Cartn_z
_atom_site.occupancy
_atom_site.label_entity_id
_atom_site.auth_asym_id
_atom_site.B_iso_or_equiv
_atom_site.pdbx_PDB_model_num
HETATM 1 FE FE . FE2 . 1 ? B 13.286 -26.080 -1.638 1.000 1 %(chn)s 37.120 1
HETATM 2 C C . PZA . 1 ? C 6.365 -26.157 -2.906 1.000 3 %(chn)s 0 1
#
#
loop_
_atom_type.symbol
C
FE
#
"""

data_lst = []
# Using 'X' as _atom_site.auth_asym_id works.
prd = PdbxReader(StringIO(cif_fragment % {"chn": "X"}))
prd.read(data_lst)

# Using '_' does not.
prd = PdbxReader(StringIO(cif_fragment % {"chn": "_"}))
prd.read(data_lst)
```

**Comment by epeisach** [comment]
The issue is that according to the spec - a data item starting with underscore needs to be quoted.

https://www.iucr.org/resources/cif/spec/version1.1/cifsyntax

A data value that starts with an underscore is believed to be the start of a new data item (Tag) -- unless quoted.

Technically speaking - a Tag must start with a "_" followed by one or more non-blank characters. - which does not apply here

The specification though - does not allow for _ as a value unless quoted - or in a semi-colon multi-line value. Non-quoted - It does not appear to be allowed.


So - I believe you are actually producing a file that is not specification compliant - unless you see a way for a "value" to be just an underscore without quoting.

**Comment by bienchen** [comment]
OK, I was expecting [CifCheck](https://github.com/rcsb/cpp-dict-pack.git) to show format violations, which it does not in this case.
